export const ADD_NEW_CATEGORY = 'ADD_NEW_CATEGORY';
export const SET_SELECTED_CATEGORY = 'SET_SELECTED_CATEGORY';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const CLEAR_SELECTED_CATEGORY = 'CLEAR_SELECTED_CATEGORY';
export const LOAD_CATEGORIES = 'LOAD_CATEGORIES';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
